spring:
  application:
    name: PopularVote

  r2dbc:
    url: r2dbc:mysql://localhost:3306/popular-vote
    username: root
    password: my-secret-pw

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        web: DEBUG