spring:
  application:
    name: PopularVote

  r2dbc:
    url: r2dbc:mysql://localhost:3306/popular-vote
    username: root
    password: my-secret-pw

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-q6tmxzhgp6abgb2w.us.auth0.com/
          audience: http://popular-vote.com

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        web: DEBUG