spring:
  application:
    name: PopularVote

  r2dbc:
    url: r2dbc:mysql://localhost:3306/popular-vote
    username: root
    password: my-secret-pw

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-q6tmxzhgp6abgb2w.us.auth0.com/
          audience: http://popular-vote.com
      client:
        registration:
          internal-client:
            client-id:
            client-secret:
            authorization-grant-type: client_credentials
            scope: update:users
            client-authentication-method: client_secret_post
            provider: internal-provider
        provider:
          internal-provider:
            token-uri:
auth0:
  management:
    audience: https://dev-q6tmxzhgp6abgb2w.us.auth0.com/api/v2/

roles:
  citizen-role-id:
  read-only-citizen-role-id:
  politician-role-id:

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        web: DEBUG